version: "3"
services:
  postgres:
    container_name: keycloak_db
    image: postgres
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "6543:5432"

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak
    ports:
      - "9000:8080"
      - "9001:8443" # for https
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak_db
      KEYCLOAK_DATABASE_USER: root
      KEYCLOAK_DATABASE_PASSWORD: root
#       # Security
#      KEYCLOAK_ENABLE_TLS: false
#      KEYCLOAK_TLS_TRUSTSTORE_FILE: /opt/bitnami/keycloak/certs/keycloak.truststore.jks/server.jks
#      KEYCLOAK_TLS_KEYSTORE_FILE: /opt/bitnami/keycloak/certs/keycloak.keystore.jks/server.jks
#      KEYCLOAK_TLS_TRUSTSTORE_PASSWORD: password
#      KEYCLOAK_TLS_KEYSTORE_PASSWORD: password
#      KEYCLOAK_TLS_CREATE_KEYSTORE: true

      #for https
#      KC_HTTP_ENABLED: true
#      KC_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/localhostcrt.pem
#      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/localhostkey.pem
    volumes:
      - ./store/:/opt/bitnami/keycloak/certs/keycloak.keystore.jks
      - ./store/:/opt/bitnami/keycloak/certs/keycloak.truststore.jks
      - ./certs/:/opt/bitnami/keycloak/certs

    depends_on:
      - postgres

volumes:
  keycloak_db_data:
    driver: local
