version: "3"
services:
  postgres:
    container_name: keycloak_db
    image: postgres
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "6543:5432"

  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak_db
      KEYCLOAK_DATABASE_USER: root
      KEYCLOAK_DATABASE_PASSWORD: root
    depends_on:
      - postgres

volumes:
  keycloak_db_data:
    driver: local
