logging:
  level:
    root: info
    org:
      springframework:
        security: trace

server:
  port: 5000
  ssl:
    enabled: false
    key-alias: localhost
    key-store: classpath:server.jks
    key-store-type: jks
    key-store-password: password
    key-password: password
    trust-store: classpath:server.jks
    trust-store-password: password
