version: "3"
services:
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - "5672:5672" # default rabbitmq port
      - "15672:15672" # UI port
      - "15674:15674" # RabbitMQ STOMP (WebSocket) port
      - "61613:61613" # STOMP port
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
#      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"