spring:
  #  datasource:
  #    username: root
  #    password: root
  #    url: jdbc:mysql://localhost/sni-chat?createDatabaseIfNotExist=true
  jpa:
    show-sql: false
  application:
    name: "backend"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:9000/realms/my-realm}

logging:
  level:
    org:
      springframework:
        security: trace
    root: info

app:
  cors:
    allowedOrigins: https://localhost:4200, http://localhost:4200

server:
  port: ${PORT:8080}
  ssl:
    enabled: ${SSL_ENABLE:true}
    key-alias: chatapp
    key-store: classpath:certs/keystore.p12
    key-store-type: pkcs12
    key-store-password: password
    key-password: password
