spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost/sni-chat?createDatabaseIfNotExist=true
  jpa:
    show-sql: false
  application:
    name: "backend"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:9000/realms/my-realm}

logging:
  level:
    org:
      springframework:
        security: trace
    root: info


server:
  port: 8080
  ssl:
    enabled: false
#    key-alias: localhost
#    key-store: classpath:server.jks
#    key-store-type: jks
#    key-store-password: password
#    key-password: password
#    trust-store: classpath:server.jks
#    trust-store-password: password
#    certificate: classpath:localhostcrt.pem
#    certificate-private-key: classpath:localhostkey.pem
